name: All-in-One Backtest

on:
  workflow_dispatch:
    inputs:
      path:
        description: "Path to CSV (optional). Falls back to outputs/prob_enriched.csv -> data/raw/vigfree_matches.csv -> data/raw/odds/sample_odds.csv"
        required: false
        default: ""
      edge_bands:
        description: "Odds band for the chosen side (e.g. 1.2,2.0|2.0,3.2|3.2,4.0). Single config uses the FIRST band."
        required: true
        default: "1.2,2.0|2.0,3.2|3.2,4.0"
      staking:
        description: "Staking method"
        required: true
        default: "kelly"
        type: choice
        options: ["kelly","flat"]
      kelly_scale:
        description: "Kelly scaler (0.5 = half Kelly, for flat: fraction of bankroll per bet)"
        required: true
        default: "0.5"
      bankroll:
        description: "Starting bankroll (units)"
        required: true
        default: "1000"
      min_edge:
        description: "Minimum true edge to consider (0.00 = none)"
        required: true
        default: "0.00"

jobs:
  backtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy

      - name: Run all-in-one (prints summary, writes job summary)
        run: |
          set -euo pipefail
          python scripts/backtest_all.py \
            --dataset "${{ inputs.path }}" \
            --min-edge "${{ inputs.min_edge }}" \
            --bands "${{ inputs.edge_bands }}" \
            --staking "${{ inputs.staking }}" \
            --kelly-scale "${{ inputs.kelly_scale }}" \
            --bankroll "${{ inputs.bankroll }}" \
            --outdir results/allinone

      - name: Upload artifacts (CSV + JSON)
        uses: actions/upload-artifact@v4
        with:
          name: all-in-one-backtest-${{ github.run_id }}
          path: |
            results/allinone/**/*.csv
            results/allinone/**/*.json
          if-no-files-found: warn
