name: All-in-One Backtest

on:
  workflow_dispatch:
    inputs:
      dataset:
        description: "Path to CSV (optional)"
        required: false
        default: ""
      min_edge:
        description: "Minimum true edge (e.g. 0.00)"
        required: true
        default: "0.00"
      staking:
        description: "kelly or flat"
        required: true
        default: "kelly"
      kelly_scale:
        description: "0.5 = half Kelly"
        required: true
        default: "0.5"
      bankroll:
        description: "Starting bankroll"
        required: true
        default: "1000"

jobs:
  backtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run all-in-one (prints summary, writes job summary)
        run: |
          python scripts/backtest_all.py \
            --dataset "${{ github.event.inputs.dataset }}" \
            --min-edge "${{ github.event.inputs.min_edge }}" \
            --staking "${{ github.event.inputs.staking }}" \
            --kelly-scale "${{ github.event.inputs.kelly_scale }}" \
            --bankroll "${{ github.event.inputs.bankroll }}"

      - name: Upload artifacts (CSV + HTML + MD)
        uses: actions/upload-artifact@v4
        with:
          name: all-in-one-backtest
          path: |
            results/backtests/summary.csv
            results/backtests/summary.md
            results/backtests/index.html
            results/backtests/logs/picks_cfg1.csv
            outputs/prob_enriched.csv
            outputs/edge_enriched.csv

