name: Courtsense CI

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: "YYYY-MM-DD"
        required: false
        default: "2024-01-01"
      end_date:
        description: "YYYY-MM-DD"
        required: false
        default: "2024-12-31"

jobs:
  backtest:
    runs-on: ubuntu-latest
    env:
      START: ${{ github.event.inputs.start_date }}
      END:   ${{ github.event.inputs.end_date }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas numpy
          fi

      - name: Ensure dataset exists
        run: python scripts/ensure_dataset.py

      - name: Run backtest
        run: python scripts/run_backtest.py --start "$START" --end "$END"

      - name: Append metrics to summary
        run: python scripts/append_metrics.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backtest_outputs
          path: |
            summary.md
            results.csv
            backtest_metrics.json
          if-no-files-found: ignore
