name: Matrix Backtest (Kelly + TE)

on:
  workflow_dispatch:
  push:
    paths:
      - 'scripts/**'
      - '.github/workflows/matrix_backtest.yml'

concurrency:
  group: matrix-backtest-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kelly_scale: [0.25, 0.5, 1.0]
        min_edge: [0.00, 0.02, 0.05]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Prepare enriched input (demo)
        run: |
          python scripts/prepare_backtest_input.py

      - name: Sanity check files
        run: |
          echo "PWD=$(pwd)"
          ls -al
          echo "---- scripts/"
          ls -al scripts || true
          echo "---- data/raw/odds/"
          ls -al data/raw/odds || true

      - name: Run backtest (matrix combo)
        env:
          PYTHONPATH: ./scripts:.
        run: |
          mkdir -p artifacts
          python scripts/backtest_all.py \
            --dataset "data/raw/odds/sample_odds_enriched.csv" \
            --bands "[1.2,2.0]" \
            --min_edge ${{ matrix.min_edge }} \
            --staking "kelly" \
            --kelly_scale ${{ matrix.kelly_scale }} \
            --bankroll 1000 \
            --cfg_id 1 \
            --outdir "artifacts"
          echo "---- summary.csv"
          cat artifacts/summary.csv || true

      - name: Stamp results with params
        run: |
          python - <<'PY'
          import os, pandas as pd
          a = pd.read_csv('artifacts/summary.csv')
          a['kelly_scale'] = float(os.environ['KELLY'])
          a['min_edge'] = float(os.environ['EDGE'])
          a.to_csv('artifacts/summary_labeled.csv', index=False)
          print(a.to_markdown(index=False))
          PY
        env:
          KELLY: ${{ matrix.kelly_scale }}
          EDGE: ${{ matrix.min_edge }}

      - name: Upload artifact (per combo)
        uses: actions/upload-artifact@v4
        with:
          name: matrix-${{ matrix.kelly_scale }}-${{ matrix.min_edge }}-${{ github.run_id }}
          path: artifacts/*
          retention-days: 7

  merge:
    needs: matrix
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: collected

      - name: Merge summaries
        run: |
          python - <<'PY'
          import pandas as pd, pathlib, os
          base = pathlib.Path('collected')
          files = list(base.rglob('summary_labeled.csv'))
          if not files:
            print("No summary_labeled.csv files found.")
            open('matrix_summary.csv','w').write('')
          else:
            frames = [pd.read_csv(p) for p in files]
            out = pd.concat(frames, ignore_index=True)
            cols = ['kelly_scale','min_edge','cfg_id','n_bets','total_staked','pnl','roi','end_bankroll']
            out = out[[c for c in cols if c in out.columns]]
            out.sort_values(['kelly_scale','min_edge'], inplace=True)
            out.to_csv('matrix_summary.csv', index=False)
            md = out.to_markdown(index=False)
            print(md)
            summ = os.environ.get('GITHUB_STEP_SUMMARY')
            if summ:
              with open(summ, 'a') as f:
                f.write("# Matrix Backtest Summary\n\n")
                f.write(md + "\n")
          PY

      - name: Upload merged matrix summary
        uses: actions/upload-artifact@v4
        with:
          name: matrix-merged-${{ github.run_id }}
          path: matrix_summary.csv
          retention-days: 7
