name: Matrix Backtest (Kelly + TE)

on:
  workflow_dispatch:
    inputs:
      dataset:
        description: "CSV with oa,ob,pa,pb (pre or post enrichment)"
        default: "outputs/prob_enriched.csv"
        required: true
      bands:
        description: "Bands like 2.0,2.6|2.6,3.2|3.2,4.0"
        default: "2.0,2.6|2.6,3.2|3.2,4.0"
        required: true
      staking:
        description: "kelly or flat"
        default: "kelly"
        required: true
      kelly_scale:
        description: "Kelly scaler (0.5 = half-kelly)"
        default: "0.5"
        required: true
      bankroll:
        description: "Starting bankroll (units)"
        default: "1000"
        required: true

jobs:
  backtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: >-
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install -U pip wheel
          pip install -r requirements.txt

      # ⬇️ NEW: normalize & inject edges so backtest has something to chew on
      - name: Enrich edges (EdgeSmith)
        run: |
          python scripts/edge_smith_enrich.py \
            --input  "${{ github.workspace }}/${{ github.event.inputs.dataset }}" \
            --output "${{ github.workspace }}/${{ github.event.inputs.dataset }}"

      - name: Run matrix backtest
        env:
          DATASET: ${{ github.event.inputs.dataset }}
          BANDS:   ${{ github.event.inputs.bands }}
          STAKE:   ${{ github.event.inputs.staking }}
          KSCALE:  ${{ github.event.inputs.kelly_scale }}
          BANK:    ${{ github.event.inputs.bankroll }}
        run: |
          python scripts/matrix_backtest.py \
            --input   "${DATASET}" \
            --bands   "${BANDS}" \
            --staking "${STAKE}" \
            --kelly-scale "${KSCALE}" \
            --bankroll "${BANK}" \
            --outdir  "backtests"

      - name: Summarize
        run: |
          echo "Matrix Backtest — Summary"
          echo "Dataset: ${{ github.event.inputs.dataset }}"
          echo "Bands:   ${{ github.event.inputs.bands }}"
          echo "Staking: ${{ github.event.inputs.staking }} | Kelly scale: ${{ github.event.inputs.kelly_scale }}"
          echo "Bankroll: ${{ github.event.inputs.bankroll }} units"
          echo ""
          ls -lah backtests || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: matrix-backtest-${{ github.run_id }}
          path: |
            backtests/**
            docs/backtests/**
          if-no-files-found: warn


