name: Matrix Backtest (Kelly + TE)

on:
  workflow_dispatch:
  push:
    paths:
      - 'scripts/**'
      - '.github/workflows/matrix_backtest.yml'

concurrency:
  group: matrix-backtest-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kelly_scale: [0.25, 0.5, 1.0]
        min_edge: [0.00, 0.02, 0.05]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Prepare enriched input (demo)
        run: |
          python scripts/prepare_backtest_input.py

      - name: Sanity check paths
        run: |
          echo "PWD=$(pwd)"
          ls -al
          echo "---- scripts/"
          ls -al scripts || true
          echo "---- odds/"
          ls -al data/raw/odds || true
          test -f data/raw/odds/sample_odds_enriched.csv || (echo "Missing enriched CSV" && exit 1)

      - name: Run backtest (matrix combo)
        env:
          PYTHONPATH: ./scripts:.
        run: |
          mkdir -p artifacts
          python scripts/backtest_all.py \
            --dataset "data/raw/odds/sample_odds_enriched.csv" \
            --bands "[1.2,2.0]" \
            --min_edge ${{ matrix.min_edge }} \
            --staking "kelly" \
            --kelly_scale ${{ matrix.kelly_scale }} \
            --bankroll 1000 \
            --cfg_id 1 \
            --outdir "artifacts"
          echo "---- artifacts/summary.csv"
          cat artifacts/summary.csv

      - name: Stamp results with params
        run: |
          python - <<'PY'
          import os,pandas as pd
          a=pd.read_csv('artifacts/summary.csv')
          a['kelly_scale']=float(os.environ['KELLY'])
          a['min_edge']=float(os.environ['EDGE'])
          a.to_csv('artifacts/summary_labeled.csv',index=False)
          print(a.to_markdown(index=False))
          PY
        env:
          KELLY: ${{ matrix.kelly_scale }}
          EDGE: ${{ matrix.min_edge }}

      - uses: actions/upload-artifact@v4
        with:
          name: matrix-${{ matrix.kelly_scale }}-${{ matrix.min_edge }}-${{ github.run_id }}
          path: artifacts/*
          retention-days: 7

  merge:
    needs: matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - uses: actions/download-artifact@v4
        with:
          path: collected

      - name: Merge summaries
        run: |
          python - <<'PY'
          import pandas as pd, pathlib, os
          base=pathlib.Path('collected')
          files=list(base.rglob('summary_labeled.csv'))
          if not files:
            print("No summaries found.")
            open('matrix_summary.csv','w').write('')
          else:
            out=pd.concat([pd.read_csv(p) for p in files], ignore_index=True)
            cols=['kelly_scale','min_edge','cfg_id','n_bets','total_staked','pnl','roi','end_bankroll']
            out=out[[c for c in cols if c in out.columns]]
            out.sort_values(['kelly_scale','min_edge'], inplace=True)
            out.to_csv('matrix_summary.csv', index=False)
            md=out.to_markdown(index=False)
            print(md)
            if os.environ.get('GITHUB_STEP_SUMMARY'):
              with open(os.environ['GITHUB_STEP_SUMMARY'],'a') as f:
                f.write("# Matrix Backtest Summary\n\n"+md+"\n")
          PY

      - uses: actions/upload-artifact@v4
        with:
          name: matrix-merged-${{ github.run_id }}
          path: matrix_summary.csv
          retention-days: 7

