name: Matrix Backtest (Kelly + TE)

on:
  workflow_dispatch:
  push:
    paths:
      - 'scripts/**'
      - '.github/workflows/matrix_backtest.yml'

concurrency:
  group: matrix-backtest-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kelly_scale: [0.25, 0.5, 1.0]
        min_edge: [0.00, 0.02, 0.05]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Ensure enriched sample
        run: |
          python scripts/prepare_backtest_input.py

      - name: Run backtest
        run: |
          mkdir -p artifacts
          python scripts/backtest_all.py \
            --dataset "data/raw/odds/sample_odds_enriched.csv" \
            --bands "[1.2,2.0]" \
            --min_edge ${{ matrix.min_edge }} \
            --staking "kelly" \
            --kelly_scale ${{ matrix.kelly_scale }} \
            --bankroll 1000 \
            --cfg_id 1 \
            --outdir "artifacts"

      - name: Stamp results with params
        run: |
          python - <<'PY'
          import pandas as pd, os
          a = pd.read_csv('artifacts/summary.csv')
          a['kelly_scale'] = float(os.environ['KELLY'])
          a['min_edge'] = float(os.environ['EDGE'])
          a.to_csv('artifacts/summary_labeled.csv', index=False)
          PY
        env:
          KELLY: ${{ matrix.kelly_scale }}
          EDGE: ${{ matrix.min_edge }}

      - name: Upload artifact (per combo)
        uses: actions/upload-artifact@v4
        with:
          name: matrix-${{ matrix.kelly_scale }}-${{ matrix.min_edge }}-${{ github.run_id }}
          path: artifacts/*
          retention-days: 7

  merge:
    needs: matrix
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: collected

      - name: Merge summaries
        run: |
          python - <<'PY'
          import pandas as pd, pathlib
          base = pathlib.Path('collected')
          frames = []
          for p in base.rglob('summary_labeled.csv'):
            frames.append(pd.read_csv(p))
          out = pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()
          out.to_csv('matrix_summary.csv', index=False)
          print(out.to_markdown(index=False))
          PY

      - name: Upload merged matrix summary
        uses: actions/upload-artifact@v4
        with:
          name: matrix-merged-${{ github.run_id }}
          path: matrix_summary.csv
          retention-days: 7

            results/backtests/**
            outputs/prob_enriched.csv
            outputs/edge_enriched.csv
            index.html
          if-no-files-found: warn
