name: Matrix Backtest (simple debug)

on:
  workflow_dispatch:
    inputs:
      csv_path:
        description: "Optional path to csv (defaults to outputs/prob_enriched.csv -> data/raw/vigfree_matches.csv -> data/raw/odds/sample_odds.csv)"
        required: false
      bands:
        description: "Edge bands like 1.0,2.0|2.0,3.0"
        required: false
        default: "1.0,2.0|2.0,3.0"
      staking:
        description: "staking method (kelly|flat)"
        required: false
        default: "kelly"
      kelly_scale:
        description: "Kelly scaler (0-1)"
        required: false
        default: "0.5"
      bankroll:
        description: "starting bankroll in units"
        required: false
        default: "1000"
      min_edge:
        description: "minimum true edge to consider (0.00 = none)"
        required: false
        default: "0.02"

jobs:
  backtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy

      - name: Prepare dataset -> ${{ github.event.inputs.csv_path || 'outputs/prob_enriched.csv' }}
        id: prepare
        run: |
          mkdir -p results
          CSV_IN="${{ github.event.inputs.csv_path }}"
          if [ -z "$CSV_IN" ]; then
            CSV_IN="outputs/prob_enriched.csv"
          fi
          python scripts/prepare_dataset.py --input "$CSV_IN" --out results/prob_enriched.csv
          echo "prepared=results/prob_enriched.csv" >> $GITHUB_OUTPUT

      - name: Run matrix backtest
        id: backtest_run
        run: |
          mkdir -p results/backtests logs
          python scripts/run_matrix_backtest.py \
            --dataset results/prob_enriched.csv \
            --bands "${{ github.event.inputs.bands }}" \
            --staking "${{ github.event.inputs.staking }}" \
            --kelly-scale "${{ github.event.inputs.kelly_scale }}" \
            --bankroll "${{ github.event.inputs.bankroll }}" \
            --min-edge "${{ github.event.inputs.min_edge }}" \
            --outdir results/backtests

      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: matrix-backtest-${{ github.run_id }}
          path: results/backtests
