name: Tennis Value Engine (H2H only)

on:
  schedule:
    - cron: "0 8 * * *"   # 08:00 UTC daily
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: tennis-value-engine
  cancel-in-progress: true

env:
  TZ: Europe/Amsterdam

jobs:
  picks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare dependencies
        run: |
          printf "pandas\nrequests\npytz\n" > requirements.txt

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run value engine (H2H only)
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          LOOKAHEAD_HOURS: "48"
          REGIONS: "eu,uk,us,au"
          MARKETS: "h2h"
          SPORT_KEYS: "tennis,tennis_atp,tennis_wta"
          KELLY_MIN: "0.05"
          EV_MIN: "0.00"
          MIN_CONF: "0.40"
          TOP_ROWS: "25"
          OUT_DIR: "outputs"
          SHORTLIST_FILE: "value_engine_shortlist.md"
        run: |
          python scripts/tennis_value_engine.py

      - name: Upload shortlist artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tennis-value-engine-shortlist
          path: outputs/value_engine_shortlist.md

      - name: Summarize (safe)
        if: always()
        run: |
          echo "## Rendered file" >> $GITHUB_STEP_SUMMARY
          if [ -f outputs/value_engine_shortlist.md ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            sed -n '1,200p' outputs/value_engine_shortlist.md >> $GITHUB_STEP_SUMMARY
          else
            echo "_No shortlist file produced._" >> $GITHUB_STEP_SUMMARY
          fi
