name: Tennis Kelly Scan (Spreads & Totals)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "5 * * * *"   # hourly at :05

permissions:
  contents: write

concurrency:
  group: tennis-kelly-scan
  cancel-in-progress: true

env:
  TZ: Europe/Amsterdam
  # Tunables (override in repo/Org env if you like)
  LOOKAHEAD_HOURS: "24"
  KELLY_THRESHOLD: "0.10"
  REGIONS: "eu,uk,us"
  MARKETS: "spreads,totals"
  OUTPUT_FILE: "kelly_sweet_spots.md"

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install deps
        run: |
          printf "requests\n" > requirements.txt
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scan
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          LOOKAHEAD_HOURS: ${{ env.LOOKAHEAD_HOURS }}
          KELLY_THRESHOLD: ${{ env.KELLY_THRESHOLD }}
          REGIONS: ${{ env.REGIONS }}
          MARKETS: ${{ env.MARKETS }}
          OUTPUT_FILE: ${{ env.OUTPUT_FILE }}
        run: |
          python odds_scan.py || exit 1
          # If The Odds API returns quota headers, print them (nice for debugging usage):
          echo "---- Quota (if present) ----"
          curl -sS -I "https://api.the-odds-api.com/v4/sports/tennis_atp/odds?apiKey=${ODDS_API_KEY}&regions=${REGIONS}&markets=${MARKETS}&oddsFormat=decimal&dateFormat=iso" \
            | grep -iE "x-requests-remaining|x-requests-used|x-requests-reset" || true
          echo "----------------------------"

      - name: Commit & push Markdown table
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Only add the files we actually expect to change
          git add ${{ env.OUTPUT_FILE }} odds_scan.py requirements.txt

          # Skip commit if nothing changed
          git diff --staged --quiet && { echo "No changes to commit."; exit 0; }

          git commit -m "Update Kelly sweet spots table [skip ci]"
          # Rebase to avoid push races if schedule overlaps
          git pull --rebase --autostash || true
          git push
