name: Tennis Kelly Scan (Spreads & Totals)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "5 * * * *"   # hourly at minute 5

permissions:
  contents: write

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Amsterdam
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          echo "requests\npython-dotenv\n" > requirements.txt
          pip install -r requirements.txt

      - name: Run scan
        run: |
          python odds_scan.py

      - name: Commit & push Markdown table
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add kelly_sweet_spots.md requirements.txt odds_scan.py
          git commit -m "Update Kelly sweet spots table [skip ci]" || echo "Nothing to commit"
          git push
