name: Tennis Value Engine (Daily Picks)

on:
  workflow_dispatch:
    inputs:
      input_csv:
        description: "Input odds CSV (two-sided or flat)"
        required: false
        default: "data/raw/odds/sample_odds.csv"
      gamma:
        description: "Fav/longshot stretch (1=no change)"
        required: false
        default: "1.05"
      min_edge:
        description: "Min (p_model - 1/odds) to accept a pick"
        required: false
        default: "0.02"
      edge:
        description: "True Edge booster (0.08 = TE8)"
        required: false
        default: "0.08"
      kelly_scale:
        description: "Kelly safety scaler"
        required: false
        default: "0.5"
      bankroll:
        description: "Starting bankroll"
        required: false
        default: "1000"
      max_picks:
        description: "Max picks (sorted by edge)"
        required: false
        default: "80"
      bands:
        description: "Odds bands for backtest (e.g. 2.0,2.6|2.6,3.2|3.2,4.0)"
        required: false
        default: "2.0,2.6|2.6,3.2|3.2,4.0"

jobs:
  value-engine:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ensure outputs directory
        run: mkdir -p outputs

      - name: Run daily pipeline (prob → engine → backtest → summaries)
        shell: bash
        run: |
          python scripts/run_daily_pipeline.py \
            --input "${{ github.event.inputs.input_csv }}" \
            --gamma "${{ github.event.inputs.gamma }}" \
            --min-edge "${{ github.event.inputs.min_edge }}" \
            --edge "${{ github.event.inputs.edge }}" \
            --kelly-scale "${{ github.event.inputs.kelly_scale }}" \
            --bankroll "${{ github.event.inputs.bankroll }}" \
            --max-picks "${{ github.event.inputs.max_picks }}" \
            --bands "${{ github.event.inputs.bands }}"

      - name: Publish summaries
        if: always()
        shell: bash
        run: |
          echo "## Tennis Value — Daily Picks" >> "$GITHUB_STEP_SUMMARY"
          [ -f outputs/engine_summary.md ] && cat outputs/engine_summary.md >> "$GITHUB_STEP_SUMMARY" || echo "No engine_summary.md" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          [ -f outputs/pipeline_summary.md ] && cat outputs/pipeline_summary.md >> "$GITHUB_STEP_SUMMARY" || echo "No pipeline_summary.md" >> "$GITHUB_STEP_SUMMARY"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: value-engine-output
          path: |
            value_picks_pro.csv
            outputs/**
          if-no-files-found: warn
