name: Tennis Value Engine (Unified)

on:
  schedule:
    - cron: "0 8 * * *"   # 08:00 UTC daily
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: tennis-value-engine
  cancel-in-progress: true

jobs:
  value:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      # fetch-depth:0 so we can commit later without weird histories
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare requirements
        run: |
          printf "pandas\nrequests\n" > requirements.txt

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ==== RUN THE ENGINE ====
      # Secrets MUST be set in this step's env (just like your working workflow)
      - name: Run unified engine
        env:
         ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}   # critical
         SPORT_KEYS: "tennis"                        # generic key your plan supports
         REGIONS: "eu,uk,us,au"
         MARKETS: "h2h,spreads,totals"
         LOOKAHEAD_HOURS: "36"                       # widen if needed
         KELLY_MIN: "0.05"
         EV_MIN: "0.00"
         TOP_ROWS: "25"
         TZ: "Europe/Amsterdam"
         OUT_DIR: "outputs"
         SHORTLIST_FILE: "value_engine_shortlist.md"
        run: |
         set -euo pipefail
         [ -n "${ODDS_API_KEY:-}" ] || { echo "ERROR: ODDS_API_KEY is not set"; exit 1; }
         python scripts/tennis_value_engine.py


      - name: Commit & push shortlist
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add outputs/value_engine_shortlist.md scripts/tennis_value_engine.py requirements.txt
          git diff --staged --quiet && { echo "No changes to commit."; exit 0; }
          git commit -m "Update unified tennis shortlist [skip ci]"
          git pull --rebase --autostash || true
          git push
