name: Tennis Kelly Scan (Spreads & Totals)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "5 * * * *"   # hourly at :05

permissions:
  contents: write

concurrency:
  group: tennis-kelly-scan
  cancel-in-progress: true

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Amsterdam
      ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
      PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
      PUSHOVER_APP_TOKEN: ${{ secrets.PUSHOVER_APP_TOKEN }}
      # Tunables
      WINDOW_HOURS: "24"        # only matches starting in next N hours
      EDGE_THRESHOLD: "0.20"    # show bets with edge >= 20%
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          printf "requests\npython-dotenv\npytz\n" > requirements.txt
          pip install -r requirements.txt

      - name: Run scan
        run: |
          python odds_scan.py

      - name: Commit & push Markdown table
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add kelly_sweet_spots.md requirements.txt odds_scan.py
          git commit -m "Update Kelly sweet spots table [skip ci]" || echo "Nothing to commit"
          git push
