name: Tennis Engine DEBUG

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    env:
      STATE_DIR: state
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Show BEFORE
        run: |
          python scripts/debug_show_trade_log.py --state-dir "${STATE_DIR}" --label "BEFORE"

      - name: Purge SYN*
        run: |
          python scripts/purge_synthetic.py --state-dir "${STATE_DIR}"

      - name: Show AFTER
        run: |
          python scripts/debug_show_trade_log.py --state-dir "${STATE_DIR}" --label "AFTER"
