name: Tennis Value Engine (Clean H2H)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "5 6 * * *"   # change as you like

permissions:
  contents: read

concurrency:
  group: tennis-value-engine
  cancel-in-progress: true

env:
  TZ: Europe/Amsterdam

jobs:
  picks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      # >>> Run YOUR model here. Do NOT enforce any filename.
      # Example (replace with your real command):
      - name: Run model
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          set -euo pipefail
          # e.g.:
          # python tennis_value_engine.py
          # (your script should write one or more CSVs to the workspace)

      - name: Filter & dedupe H2H; publish summary
        run: |
          python - <<'PY'
          import pandas as pd, glob, os, sys, re

          def norm(s): return re.sub(r'[^a-z0-9]', '', str(s).lower())

          # 1) Find the best CSV produced by the model.
          csvs = glob.glob("**/*.csv", recursive=True)
          if not csvs:
              print("ERROR: No CSV files found after model run.", file=sys.stderr)
              sys.exit(1)

          # Prefer names that look like "Tennis Value Engine Unified..."
          def score(path):
              base = norm(os.path.basename(path))
              # prefer "tennis value engine unified", then larger files
              prefer = all(k in base for k in ["tennis","value","engine","unified"])
              return (prefer, os.path.getsize(path))

          csvs.sort(key=score, reverse=True)

          # 2) Column remapping (tolerant to naming).
          def remap_columns(df):
              want = {
                  'selection': ['selection','player','pick'],
                  'opponent':  ['opponent','opp'],
                  'market':    ['market','mkt'],
                  'kelly':     ['kelly','kellyfraction','k'],
                  'ev/u':      ['ev/u','evu','evperu','ev','edge'],
                  'odds':      ['odds','price','decimalodds'],
                  'p_model':   ['p_model','pmodel','prob','prob_model'],
                  'p_fair':    ['pfair','p_fair','prob_fair','fairprob'],
              }
              nm = {norm(c): c for c in df.columns}
              out = {}
              for canon, aliases in want.items():
                  for a in aliases:
                      if a in nm:
                          out[canon] = nm[a]; break
              for r in ['selection','opponent','market','kelly','ev/u']:
                  if r not in out:
                      raise KeyError(f"Missing required column: {r}")
              return out

          df, src, cols = None, None, None
          for f in csvs:
              try:
                  cand = pd.read_csv(f)
              except Exception:
                  continue
              try:
                  cols = remap_columns(cand)
                  df, src = cand.copy(), f
                  break
              except Exception:
                  continue

          if df is None:
              print("ERROR: CSVs found, but none had required columns.", file=sys.stderr)
              sys.exit(1)

          # 3) Coerce numerics
          for c in [cols['kelly'], cols['ev/u']]:
              df[c] = pd.to_numeric(df[c], errors='coerce')
          if 'odds' in cols:
              df[cols['odds']] = pd.to_numeric(df[cols['odds']], errors='coerce')

          # 4) Keep H2H only + filters
          df = df[df[cols['market']].astype(str).str.upper().eq('H2H')].copy()
          df = df[(df[cols['kelly']] > 0.05) & (df[cols['ev/u']] > 0)].copy()

          # 5) Dedupe per unordered matchup (keep highest Kelly, then EV/u, then Odds)
          def pair_key(a,b):
              a,b = str(a).strip(), str(b).strip()
              return " | ".join(sorted([a,b]))
          df['__pair__'] = [pair_key(a,b) for a,b in zip(df[cols['selection']], df[cols['opponent']])]

          sort_cols, asc = [cols['kelly'], cols['ev/u']], [False, False]
          if 'odds' in cols: sort_cols.append(cols['odds']); asc.append(False)
          df.sort_values(sort_cols, ascending=asc, inplace=True)
          df = df.drop_duplicates(['__pair__'], keep='first').copy()
          df.drop(columns='__pair__', inplace=True)

          # 6) Finalize and output
          df['Bet'] = 'YES'
          rename = {
              cols['market']:'Market',
              cols['selection']:'Selection',
              cols['opponent']:'Opponent',
              cols['kelly']:'Kelly',
              cols['ev/u']:'EV/u'
          }
          if 'odds' in cols:    rename[cols['odds']] = 'Odds'
          if 'p_model' in cols: rename[cols['p_model']] = 'p_model'
          if 'p_fair' in cols:  rename[cols['p_fair']]  = 'p_fair'
          df = df.rename(columns=rename)

          preferred = ['Tour','Market','Selection','Opponent','Odds','p_model','p_fair','EV/u','Kelly','Conf','Bet','Start (UTC)','Books','Source']
          order = [c for c in preferred if c in df.columns] or df.columns.tolist()
          df = df[order]

          out_csv = "value_filtered_h2h.csv"
          df.to_csv(out_csv, index=False)

          def gfm(t):
              if t.empty: return "_No H2H picks passed filters._"
              lines = ["| " + " | ".join(t.columns) + " |",
                       "| " + " | ".join(["---"]*len(t.columns)) + " |"]
              for _, r in t.iterrows():
                  lines.append("| " + " | ".join(str(r[c]) for c in t.columns) + " |")
              return "\n".join(lines)

          with open(os.environ.get("GITHUB_STEP_SUMMARY","/tmp/gh_summary.md"), "a") as fh:
              fh.write(f"# Clean H2H Picks (source: {src})\n\n" + gfm(df) + "\n")

          print(f"Source: {src}  ->  value_filtered_h2h.csv  (rows kept: {len(df)})")
          PY

      - name: Upload filtered picks
        uses: actions/upload-artifact@v4
        with:
          name: value_filtered_h2h
          path: value_filtered_h2h.csv
          if-no-files-found: error
