name: Tennis Value Engine (Daily Picks)

on:
  workflow_dispatch:
    inputs:
      input_csv:
        description: "Input odds CSV"
        required: false
        default: "data/raw/odds/sample_odds.csv"
      min_edge_te:
        description: "TE (model tilt) target edge"
        required: false
        default: "0.08"
      kelly_scale:
        description: "Kelly scale (0..1)"
        required: false
        default: "0.5"
      bankroll:
        description: "Initial bankroll for backtest"
        required: false
        default: "1000"
      bands:
        description: "Odds bands"
        required: false
        default: "2.0,2.6|2.6,3.2|3.2,4.0"
      run_prob_diag:
        description: "Print probability diagnostics first"
        required: false
        default: "false"

jobs:
  value-engine:
    runs-on: ubuntu-latest
    env:
      INPUT_CSV: ${{ github.event.inputs.input_csv }}
      MIN_EDGE_TE: ${{ github.event.inputs.min_edge_te }}
      KELLY_SCALE: ${{ github.event.inputs.kelly_scale }}
      BANKROLL: ${{ github.event.inputs.bankroll }}
      BANDS: ${{ github.event.inputs.bands }}
      RUN_PROB_DIAG: ${{ github.event.inputs.run_prob_diag }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ensure outputs dir
        run: mkdir -p outputs

      - name: Run probability diagnostics (optional)
        if: env.RUN_PROB_DIAG == 'true'
        run: |
          python scripts/compute_prob_vigfree.py --input "$INPUT_CSV" --out outputs/prob_enriched.csv
          python scripts/check_probabilities.py --input outputs/prob_enriched.csv --min-edge 0.02 --te "${MIN_EDGE_TE}" \
            | tee outputs/diag_prob.md

      - name: Run daily pipeline (prob → engine → backtest)
        run: |
          set -euo pipefail

          python scripts/compute_prob_vigfree.py \
            --input "$INPUT_CSV" \
            --out outputs/prob_enriched.csv

          python scripts/tennis_value_engine.py \
            --input outputs/prob_enriched.csv \
            --out-final outputs/picks_final.csv \
            --summary outputs/engine_summary.md \
            --stake-mode kelly \
            --kelly-scale "${KELLY_SCALE}" \
            --kelly-cap 0.2 \
            --min-edge 0.00 \
            --edge "${MIN_EDGE_TE}" \
            --bankroll "${BANKROLL}"

          python scripts/run_matrix_backtest.py \
            --input outputs/prob_enriched.csv \
            --outdir outputs \
            --bands "${BANDS}" \
            --stake-mode kelly \
            --edge "${MIN_EDGE_TE}" \
            --kelly-scale "${KELLY_SCALE}" \
            --bankroll "${BANKROLL}" || true

          if [ ! -s outputs/matrix_rankings.csv ]; then
            echo "No matrix rankings produced; falling back to synthetic backtest csv."
            printf "odds,p,result\n" > outputs/synthetic_backtest.csv
            printf "2.10,0.55,1\n2.40,0.45,0\n2.80,0.40,1\n2.00,0.35,0\n3.20,0.35,0\n2.30,0.48,1\n3.50,0.32,0\n" >> outputs/synthetic_backtest.csv

            python scripts/run_matrix_backtest.py \
              --input outputs/synthetic_backtest.csv \
              --outdir outputs \
              --bands "${BANDS}" \
              --stake-mode kelly \
              --edge "${MIN_EDGE_TE}" \
              --kelly-scale "${KELLY_SCALE}" \
              --bankroll "${BANKROLL}" || true
          fi

      - name: Build combined pipeline summary (always)
        if: always()
        run: |
          python scripts/merge_report.py \
            --engine-md outputs/engine_summary.md \
            --matrix-metrics outputs/backtest_metrics.json \
            --matrix-rankings outputs/matrix_rankings.csv \
            --matrix-results outputs/results.csv \
            --out outputs/pipeline_summary.md

      - name: Publish summaries to job log
        if: always()
        run: |
          echo "## Pipeline Summary" >> "$GITHUB_STEP_SUMMARY"
          if [ -s outputs/pipeline_summary.md ]; then
            cat outputs/pipeline_summary.md >> "$GITHUB_STEP_SUMMARY"
          else
            echo "_No pipeline summary produced._" >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: value-engine-output
          path: |
            outputs/*.md
            outputs/*.csv
            outputs/*.json
          if-no-files-found: warn

